apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: development
  labels:
    app: iot-gitlab
spec:
  description: GitLab Project to deploy our app locally
  sourceRepos:
    - "http://178.62.244.89:9999/root/*"
  destinations:
    - namespace: gitlab
      server: https://kubernetes.default.svc
  orphanedResources:
    warn: false

