apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: development
  labels:
    app: iot-argocd
spec:
  description: Our ArgoCD Project to deploy our app locally
  sourceRepos:
    - "https://github.com/wen/*"
  destinations:
    - namespace: dev
      server: https://kubernetes.default.svc
  orphanedResources:
    warn: false
