# -*- mode: ruby -*-
# vi: set ft=ruby :

CPUS      = 4
MEMORY    = 4096
BOX       = "centos/7"
MASTER    = "suchoS"
IP_MASTER = "192.168.42.110"

master_script = <<-SHELL
  curl -sfL https://get.k3s.io \
    | \
      sh -s - \
        server \
          --write-kubeconfig-mode=644 \
          --flannel-iface=eth1
  # Failed to pull image issue, https://github.com/k3s-io/k3s/issues/4858#issuecomment-1063786817 & https://yuanji.dev/devops/kubernetes/k3s/#troubleshooting
  mkdir -p /run/systemd/resolve/
  echo -e "nameserver 8.8.8.8\nnameserver 8.8.4.4" >> /run/systemd/resolve/stub-resolv.conf
  ln -rsf /run/systemd/resolve/stub-resolv.conf /etc/resolv.conf
  sed "s/127.0.0.1/#{IP_MASTER}/" /etc/rancher/k3s/k3s.yaml > /vagrant/k3s.yaml
  /usr/local/bin/kubectl -n kube-system apply -f /vagrant/confs
  yum install -y net-tools # install ifconfig
SHELL

Vagrant.configure("2") do | config |
  config.vm.box = BOX
  config.vm.provider "virtualbox" do | vb |
    vb.cpus = CPUS
    vb.memory = MEMORY
  end
  config.vm.define MASTER do | master |
    master.vm.hostname = MASTER
    master.vm.provision "shell", inline: master_script
    master.vm.network "private_network", ip: IP_MASTER, hostname: true
  end
  config.vm.synced_folder ".", "/vagrant", type: "nfs"
  config.vm.network "forwarded_port", guest: 80, host: 80, protocol: "tcp"
  config.vm.network "forwarded_port", guest: 6443, host: 6443, protocol: "tcp"
end
