# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # common config
  config.vm.box = "centos/7"
  config.vm.provider "virtualbox" do |v|
    v.cpus = 1
    v.memory = 1024
    v.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
    v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
  end
  config.vm.provision "shell", inline: "yum install -y net-tools" # install ifconfig

  # master config
  config.vm.define "yewenS" do |master|
    master.vm.hostname = "yewenS"
    master.vm.network "private_network", ip: "192.168.42.110"
    master.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--name", "yewenS"]
    end
    master.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "/tmp/id_rsa.pub"
    master.vm.provision "shell", path: "scripts/master.sh"
  end

  # worker config
  config.vm.define "yewenSW" do |worker|
    worker.vm.hostname = "yewenSW"
    worker.vm.network "private_network", ip: "192.168.42.111"
    worker.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--name", "yewenSW"]
    end
    config.vm.provision "file", source: "~/.ssh/id_rsa", destination: "/tmp/id_rsa"
    worker.vm.provision "shell", path: "scripts/worker.sh"
  end
end
