CPUS = 4
MEMORY = 4096
BOX = "centos/7"
MASTER = "k3S"
WORKER = "k3SW"
IP_MASTER = "192.168.42.110"
IP_WORKER = "192.168.42.111"

common = <<-SHELL
	sudo yum -y install vim tree net-tools telnet git python3
	sudo echo "autocmd filetype yaml setlocal ai ts=2 sw=2 et" > /home/vagrant/.vimrc
	sudo echo "alias python=/usr/bin/python3" >> /home/vagrant/.bashrc
	sed -i 's/ChallengeResponseAuthentication no/ChallengeResponseAuthentication yes/g' /etc/ssh/sshd_config
	sudo systemctl restart sshd
    SHELL


Vagrant.configure("2") do | config |
  config.vm.box = BOX
  # Synced folder between host and the guest machine
  config.vm.synced_folder ".", "/vagrant", type: "nfs"
  config.vm.provider "virtualbox" do | vb |
    vb.cpus = CPUS
    vb.memory = MEMORY
    # Enable NAT hosts DNS resolver
    vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    # Reduce the time sync threshold
    vb.customize [ "guestproperty", "set", :id, "/VirtualBox/GuestAdd/VBoxService/--timesync-set-threshold", 10000 ]
  end
  
  config.vm.define "glab" do |gitlab|
  	gitlab.vm.network "forwarded_port", guest: 9999, host: 9999, protocol: "tcp"
  	gitlab.vm.box = "debian/buster64"
	gitlab.vm.hostname = "glab"
  	gitlab.vm.box_url = "debian/buster64"
	gitlab.vm.network "private_network", ip: "192.168.42.99"
	gitlab.vm.provision "shell", inline: <<-SHELL
		sed -i 's/ChallengeResponseAuthentication no/ChallengeResponseAuthentication yes/g' /etc/ssh/sshd_config
		service ssh restart
	SHELL
	gitlab.vm.provision "shell", path: "scripts/install_gitlab.sh"
  end
end
