apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: iot-argocd-development
spec:
  project: development
  source:
    repoURL: https://github.com/sungyongcho/iot-argocd.git
    targetRevision: HEAD
    path: manifests
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
